"""Every prompt RUAI sends to a model.

All three checks ask for the same JSON envelope, which is what lets three very
different analyses collapse into one `Verdict`:

    {"score": 0.0-1.0, "signals": [{label, detail, severity}], "note": "..."}

`score` always means the same thing: 0 is "nothing wrong here", 1 is "this is
certainly not what it claims to be".

Signal `detail` text is shown to the reader verbatim, so the prompts insist on
plain language. That instruction is doing real work — without it the models
reach for "temporal incoherence in the subject's periocular region".
"""

from __future__ import annotations

_ENVELOPE = """Reply with JSON only. No prose before or after it.

{
  "score": <number between 0.0 and 1.0>,
  "signals": [
    {
      "label": "<four to six words naming what you found>",
      "detail": "<one sentence a 70-year-old with no technical background would understand>",
      "severity": "low" | "medium" | "high"
    }
  ],
  "note": "<two or three sentences explaining how you reached the score>"
}

Return an empty "signals" list when you find nothing worth reporting."""

_PLAIN_LANGUAGE = """Write every "detail" in plain English. Short sentences.
No jargon, no technical vocabulary, no hedging phrases. Say "her hand changes
shape", not "anatomical inconsistency in the manual region"."""


def video_frame_prompt(context: str) -> str:
    """Prompt for judging a single still frame."""
    return f"""You are looking at one frame from a video. Decide whether the
video was generated by AI, and how confident you are.

WHAT COUNTS AS EVIDENCE — physical impossibility, not unusual appearance:
- Bodies or objects bending in ways that are anatomically or mechanically impossible
- Hands and fingers with the wrong count, or joints folding backwards
- Text, logos or signage that dissolves into nonsense letterforms
- Objects merging into each other, or edges that melt into the background
- Faces where features sit at impossible positions relative to each other

WHAT DOES NOT COUNT — ordinary video looks like this all the time:
- Colour grading, filters, beauty filters, cinematic looks
- Compression blocking, blur, grain, low resolution
- Motion blur, camera shake, shallow depth of field
- Studio lighting that looks "too perfect"
- Overlays, captions, graphics, watermarks
- An unusual camera angle that makes a hand or limb look strange
- Skilled people performing precisely, or a scene that is simply well produced

SCORING:
- 0.0-0.2  Nothing beyond ordinary production and compression
- 0.3-0.6  Something is off, but a real camera could plausibly produce it
- 0.7-1.0  At least one thing here cannot physically happen

Be strict. A real video wrongly called fake costs the viewer their trust in
this tool. When the evidence is only "it looks a bit odd", the score is low.

{context}
{_PLAIN_LANGUAGE}

{_ENVELOPE}"""


def video_sequence_prompt(context: str, frame_count: int, gap_ms: float) -> str:
    """Prompt for judging consecutive frames, where AI generation shows up most."""
    return f"""You are looking at {frame_count} consecutive frames from one
video, about {gap_ms:.0f} milliseconds apart, in order. Decide whether the
video was generated by AI.

Compare the frames against each other. Generated video usually survives a
single still and falls apart across time.

WHAT COUNTS AS EVIDENCE:
- Something present in one frame and gone in the next with nowhere to go
- Objects sliding without anyone moving them, or drifting against gravity
- A limb, finger or facial feature that changes count, length or shape between frames
- Position jumps too large for the time elapsed, given the apparent speed
- Solid things flexing like liquid, or passing through each other
- Backgrounds that reflow or reorganise as the camera moves

WHAT DOES NOT COUNT:
- A cut to a different shot, or a deliberate transition
- Slow motion, time-lapse, or speed ramping
- Consistent filters, colour grading or green screen
- Compression artefacts that move with the encoding, not the subject
- Camera shake, motion blur, or a subject leaving the frame naturally

SCORING:
- 0.0-0.2  Everything between frames is physically ordinary
- 0.3-0.6  One transition is strange but has a plausible everyday explanation
- 0.7-1.0  At least one change between frames is physically impossible

Be strict. Edited footage is not fake footage.

{context}
{_PLAIN_LANGUAGE}

{_ENVELOPE}"""


def message_prompt(context: str, message: str, local_flags: str) -> str:
    """Prompt for judging a chat message sent to an older adult."""
    return f"""You are protecting an older adult from fraud. Decide whether
this message is a scam.

{context}
MESSAGE:
\"\"\"{message}\"\"\"

A keyword scan already noticed: {local_flags}

JUDGE BY BEHAVIOUR, NOT TOPIC. Scams almost always do at least one of these:
- Demand a decision faster than the situation warrants
- Ask for money by a route that cannot be reversed: gift cards, wire transfer,
  crypto, payment apps to a stranger
- Ask for secrets: passwords, one-time codes, Social Security number, bank details
- Claim authority — a bank, the IRS, Social Security, Medicare, Microsoft,
  Apple, Amazon — while contacting the person out of the blue
- Claim to be a relative in trouble and ask that nobody else be told
- Offer a prize, refund or return that was never applied for
- Build a relationship over time and then introduce a money problem

WHAT IS NOT A SCAM: ordinary messages that merely mention money, family,
health or urgency. A daughter writing "call me when you can, it's urgent" is
not fraud. A real bank confirming a payment the person made is not fraud.

SCORING:
- 0.0-0.2  Ordinary message
- 0.3-0.6  Uses one pressure tactic; could be legitimate
- 0.7-1.0  Matches a known fraud pattern

Err toward warning when money or secrets are requested by an unexpected
sender. Err toward silence when the message is merely emotional.

{_PLAIN_LANGUAGE}

{_ENVELOPE}"""


def article_prompt(context: str, text: str) -> str:
    """Prompt for judging a news article or a forwarded claim."""
    return f"""You are fact-checking a story that an older adult has been sent
or has found online. Decide how likely it is to be false or misleading.

{context}
TEXT:
\"\"\"{text}\"\"\"

CHECK:
- Does the central claim conflict with well-established facts?
- Are there specific, checkable details, or only vague assertions?
- Does it name sources that can be verified, or only "experts say"?
- Does the emotional pitch outrun the evidence?
- Is it urging the reader to share, buy, donate, or panic?
- Could this be a real story stripped of context, or an old story recycled?

Say so plainly when you cannot verify something. "I do not know" scores near
the middle; it is not evidence of falsehood.

SCORING:
- 0.0-0.2  Consistent with what is known
- 0.3-0.6  Unverifiable, missing context, or misleadingly framed
- 0.7-1.0  Central claim conflicts with established fact

{_PLAIN_LANGUAGE}

{_ENVELOPE}"""
